# # ENPOINT PARA CREAR Grupo
#   POST http://localhost:4000/api/grupo/nuevo HTTP/1.1
#     Content-Type: application/json

# {
#     "nombre": "Grupo 1",
#     "carrera": "Energias Renovables",
#     "id_materia": 6
# }

# ENPOINT PARA OBTENER TODOS LOS GRUPOS
#   GET http://localhost:4000/api/grupo/ HTTP/1.1

# # ENPOINT PARA ACRUALIZAR Grupo
#   PUT  http://localhost:4000/api/grupo/1 HTTP/1.1
#     Content-Type: application/json

# {
#     "nombre": "Grupo 6A",
#     "carrera": "Tecnologias de la Informacion",
#     "id_materia": 6
# }

# Enpoint para obtenr todos los alumnos registrados en el grupo 5
  GET http://localhost:4000/api/grupo/5 HTTP/1.1
